### ISSUE TITLE
Permission to use the clock inside CyBear Jinni app

### ISSUE THREAD

**Issue by guyluz11** [Dwite/Scenery-FlutterClock#2]
Hello Dwite

My name is Guy Luz and I am the CEO of CyBear Jinni.
**CyBear Jinni** is an open source smart home company.

We are thinking of integrating your clock layout inside our app and would love to get your permission to do so.

Some of the smart home functionality that we imagining is to set alarm clock inside the app, this way when the user wakes up the app can start pre made routine, and if he snooze the alarm the routine will wait for him to wake up.
If the device is locked a full screen of our app will pop up and your clock will appear in that page.

Please check [CyBear Jinni github page](https://github.com/CyBear-Jinni) and tell us if this is something that you would like to be part of.

Thank you and have a great day.

**Comment by Dwite** [comment]
Hey @guyluz11 , you have my permission to use the clock and source code inside products you've mentioned.

**Comment by guyluz11** [comment]
Many thanks.
